<?php

namespace tfg\SubConocimientoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubConocimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubConocimientoRepository extends EntityRepository
{
}
