tfg\DisciplinaBundle\Entity\Disciplina:
    type: entity
    table: null
    repositoryClass: tfg\DisciplinaBundle\Repository\DisciplinaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
            unique: true
        descripcion:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
