<?php

namespace tfg\VisitasOfertaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VisitasOfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitasOfertaRepository extends EntityRepository
{
}
