conocimientos:
    resource: "@ConocimientosBundle/Resources/config/routing.yml"
    prefix:   /

sub_conocimiento:
    resource: "@SubConocimientoBundle/Resources/config/routing.yml"
    prefix:   /

conocimiento:
    resource: "@ConocimientoBundle/Resources/config/routing.yml"
    prefix:   /

visitas_demanda:
    resource: "@VisitasDemandaBundle/Resources/config/routing.yml"
    prefix:   /

visitas_oferta:
    resource: "@VisitasOfertaBundle/Resources/config/routing.yml"
    prefix:   /

comentario_demanda:
    resource: "@ComentarioDemandaBundle/Resources/config/routing.yml"
    prefix:   /

comentario_oferta:
    resource: "@ComentarioOfertaBundle/Resources/config/routing.yml"
    prefix:   /

demanda:
    resource: "@DemandaBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /


homepage:
   pattern: /
   defaults: { _controller: TareaListadoBundle:Tarea:index }
   requirements:  { _method: "GET" }


admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
