# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      app.brochure_uploader:
          class: tfg\OfertaBundle\FileUploader
          arguments: ['%brochures_directory%']
      admin.oferta:
          class: tfg\OfertaBundle\Admin\OfertaAdmin
          arguments: [~, tfg\OfertaBundle\Entity\Oferta, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, label: Oferta }
      admin.area:
        class: tfg\AreaBundle\Admin\AreaAdmin
        arguments: [~, tfg\AreaBundle\Entity\Area, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Area }
      admin.rama:
          class: tfg\RamaBundle\Admin\RamaAdmin
          arguments: [~, tfg\RamaBundle\Entity\Rama, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, label: Rama }
      admin.disciplina:
        class: tfg\DisciplinaBundle\Admin\DisciplinaAdmin
        arguments: [~, tfg\DisciplinaBundle\Entity\Disciplina, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Disciplina }
