<?php

namespace tfg\ConocimientoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConocimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConocimientoRepository extends EntityRepository
{
}
