<?php

namespace tfg\DemandaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DemandaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandaRepository extends EntityRepository
{
}
