<?php

namespace tfg\ComentarioOfertaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioOfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioOfertaRepository extends EntityRepository
{
}
