portada:
    path:     /demandas/
    defaults: { _controller: OfertaBundle:Default:portada }

addOferta:
    path:     /addOferta/
    defaults: { _controller: OfertaBundle:Default:subirOferta }

mostrarOfertas:
    path:     /mostrarOfertas/
    defaults: { _controller: OfertaBundle:Default:mostrarOfertas }

showOferta:
    path:     /showOferta/
    defaults: { _controller: OfertaBundle:Default:showOferta }

deleteComment:
    path:     /deleteComment/
    defaults: { _controller: OfertaBundle:Default:deleteComment }
