<?php

namespace tfg\RamaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RamaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RamaRepository extends EntityRepository
{
}
