<?php

namespace tfg\VisitasDemandaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VisitasDemandaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitasDemandaRepository extends EntityRepository
{
}
