disciplina_homepage:
    path:     /disciplinas/
    defaults: { _controller: DisciplinaBundle:Default:index }
addDisciplina:
    path:     /disciplinas/addDisciplina/
    defaults: { _controller: DisciplinaBundle:Default:subirDisciplina }
mostrarDisciplinas:
        path:     /mostrarDisciplinas/
        defaults: { _controller: DisciplinaBundle:Default:mostrarDisciplinas }
