<?php

namespace ConocimientosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConocimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConocimientosRepository extends EntityRepository
{
}
