<?php

namespace tfg\AreaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends EntityRepository
{
}
