rama_homepage:
    path:     /ramas/
    defaults: { _controller: RamaBundle:Default:index }
addRama:
    path:     /ramas/addRama/
    defaults: { _controller: RamaBundle:Default:subirRama }
mostrarRamas:
        path:     /mostrarRamas/
        defaults: { _controller: RamaBundle:Default:mostrarRamas }
