<?php

namespace tfg\ComentarioDemandaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioDemandaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioDemandaRepository extends EntityRepository
{
}
